### ISSUE TITLE
LDAPS connection

### ISSUE THREAD

**Issue by SilvioSodre** [michael-o/dirctxsrc#1]
Hi Michael!
Does DirCtxSrc support LDAPS connection?
Thanks in advance!
Silvio.

**Comment by michael-o** [comment]
Yes, it supports whatever Sun's JNDI/LDAP `InitialDirContext` supports. But note that if you want to use `ldaps://` with Active Directory and Kerberos authntication, make sure that QOP is set to `auth` only because AD supports only one security layer (external, TLS) and not combined with Kerberos.

Let me know with an example if it is otherwise for you!

**Comment by SilvioSodre** [comment]
Thanks for your quick reply! I use DirCtxSrc to do a keytab file authentication to the LDAP server, so I'm using Kerberos. Does DirCtxSrc support LDAPS connection in this condition?

**Comment by michael-o** [comment]
Since you use Kerberos you don't need LDAPS at all. Just use QOP `auth-conf`. It will automatically encrypt all traffic with you security context. I have been doing this the past 10+ years.

**Comment by SilvioSodre** [comment]
Thanks for your quick reply! I changed my QOP to "auth" and now I am able to connect via LDAPS using keytab file authentication.

**Comment by michael-o** [comment]
> Thanks for your quick reply! I changed my QOP to "auth" and now I am able to connect via LDAPS using keytab file authentication.

Like I said 😁
